version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"

  # Maintain dependencies for npm/yarn
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
