name: 'is-workspace-affected'
description: 'Test if a yarn workspace is affected by changes'

branding:
  icon: check-square
  color: gray-dark

inputs:
  project-root:
    description: 'Yarn project root'
    required: false
    default: '.'

  workspace:
    description: 'Yarn workspace to check'
    required: true

  base:
    description: 'Base to compute diff'
    required: true

  pattern:
    description: 'Files to search in the diff. Relative to tested workspace root.'
    required: false
    default: '**'

outputs:
  affected:
    description: 'true if workspace is affected'

runs:
  using: node20
  main: 'dist/bundle.cjs'
