name: 'Dependabot'

on: pull_request

jobs:
  metadata:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    outputs:
      dependency-type: ${{ steps.dependabot-metadata.outputs.dependency-type }}
      package-ecosystem: ${{ steps.dependabot-metadata.outputs.package-ecosystem }}
      update-type: ${{ steps.dependabot-metadata.outputs.update-type }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.6.0

  auto-merge:
    if: ${{ needs.metadata.outputs.dependency-type == 'direct:production' && needs.metadata.outputs.package-ecosystem == 'npm_and_yarn' && needs.metadata.outputs.update_type != 'version-update:semver-major' }}
    runs-on: ubuntu-latest
    needs: [metadata]

    permissions:
      contents: write

    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: '${{ github.event.pull_request.html_url }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
