name: 'Dependabot'

on: pull_request_target

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Update bundle
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/bundle.cjs | wc -l)" -gt "0" ]; then
            echo "::notice::Detected uncommitted changes after build. Make a commit containing the changes."
          
            git config user.name github-actions
            git config user.email github-actions@github.com
          
            git add dist/bundle.*
            git commit -m 'chore: update bundle'
            git push
          fi

  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    needs: [build]

    permissions:
      pull-requests: write

    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@v1.1.1
        id: dependabot-metadata
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: '${{ github.event.pull_request.html_url }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: '${{ github.event.pull_request.html_url }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
